# Generated by Django 6.0.8 on 2026-09-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationssu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ticket_assigned', 'Ticket Assigned'), ('new_ticket', 'New Ticket'), ('new_message', 'New Message'), ('sla_breach', 'SLA Breach'), ('chat_escalated', 'Chat Escalated'), ('document_ready', 'Document Ready')], max_length=30),
        ),
    ]
