# Generated by Django 6.0.8 on 2026-09-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketssu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
